import type { Metadata } from "next";
import { Raleway as FontSans } from "next/font/google"; // Import Raleway instead of Inter
import { cn } from "@/lib/utils";
import "./globals.css";
import Footer from "@components/shared/footer";

// Configure Raleway font
const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
	weight: ["400", "500", "600", "700"], // You can choose the weights you want to use
});

export const metadata: Metadata = {
	title: "Mobile Marketplace",
	description: "Generated by Ab",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable
				)}>
				{children}
			</body>
			<Footer />
		</html>
	);
}
